/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLPass = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 306, -1, -1));

        jLApellido.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLApellido.setText("Apellido");
        getContentPane().add(jLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 344, -1, -1));

        jLPass.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLPass.setForeground(new java.awt.Color(255, 255, 255));
        jLPass.setText("Password");
        getContentPane().add(jLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 386, -1, -1));

        jTNombre.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 20));

        jTApellido.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 110, 20));

        jPassword.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, 20));

        jBLogin.setBackground(new java.awt.Color(71, 78, 194));
        jBLogin.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBLogin.setText("Login");
        jBLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 70, -1));

        jBCancel.setBackground(new java.awt.Color(71, 78, 194));
        jBCancel.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBCancel.setText("Cancel");
        jBCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 70, -1));

        jLUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 260));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        try {
                 
            String apellido = jTApellido.getText();
            String nombre = jTNombre.getText();
            int dni = Integer.parseInt(new String(jPassword.getPassword()));
            
            if (apellido.equalsIgnoreCase("ULP")&& nombre.equalsIgnoreCase("admin")&& dni == 12345) {
               // System.out.println("Acceso a Gestion de Alumnos");
                PantallaPpal pantallaPpal = new PantallaPpal(); //creo una pantallaPpal
				pantallaPpal.setVisible(true); // lo hago visible
				pantallaPpal.setLocationRelativeTo(null); // abrirlo en el centro
				dispose(); //cierra ventana de login
                
            }else {
                
//                System.out.println("Acceso de alumnos");
                AutogestionAlumnos autogestionAlumnos = new AutogestionAlumnos(alumno);
                        autogestionAlumnos.setVisible(true);
                        autogestionAlumnos.setLocationRelativeTo(null); // abrirlo en el centro
				dispose(); //cierra ventana de login
            }
//            System.out.println(" " + apellido + " " + nombre + " " + dni);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La clave debe ser numerica, verifique los datos ingresados", "Numero no valido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        dispose(); //Cerrar la ventana
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
