/*
	Trabajo práctico trasversal de la Guía 5 del curso Desarrollo de Apps
	Universidad de La Punta en el marco del proyecto Argentina Programa 4.0

	Integrantes:
		John David Molina Velarde
		Leticia Mores
		Enrique Germán Martínez
		Carlos Eduardo Beltrán
 */

package vistas;

import accesoadatos.AlumnoData;
import accesoadatos.UsuarioData;
import entidades.Alumno;
import entidades.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author John David Molina Velarde, Leticia Mores, Enrique Germán Martínez, Carlos Eduardo Beltrán
 */
public class Login extends javax.swing.JFrame {
	
	/**
	 * Constructor
	 */
    public Login() {
        initComponents();
    } //constructor

	
	
	/**
	 * Para poder poner el ícono de la ULP en la ventana
	 * @return 
	 */	
	@Override
	public Image getIconImage() { // defino el icono del jFrame
		Image retValue = Toolkit.getDefaultToolkit().
				getImage(ClassLoader.getSystemResource("imagenes/ulp_32x32.png")); //icono de la ULP
		return retValue;
	} // getIconImage
	
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLPass = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 306, -1, -1));

        jLApellido.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLApellido.setText("Apellido");
        getContentPane().add(jLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 344, -1, -1));

        jLPass.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLPass.setForeground(new java.awt.Color(255, 255, 255));
        jLPass.setText("Password");
        getContentPane().add(jLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 386, -1, -1));

        jTNombre.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 20));

        jTApellido.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 110, 20));

        jPassword.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, 20));

        jBLogin.setBackground(new java.awt.Color(71, 78, 194));
        jBLogin.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBLogin.setText("Login");
        jBLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 70, -1));

        jBCancel.setBackground(new java.awt.Color(71, 78, 194));
        jBCancel.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBCancel.setText("Cancel");
        jBCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 70, -1));

        jLUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 260));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
	/**
	 * Este método se llama cuando el usuario hace clíck en el botón Login.
	 * Se conecta a la base de datos (usando UsuarioData y AlumnoData) y 
	 * verifica si la clave es la clave maestra o la clave de un usuario
	 * administrativo (está en la bd en la tabla Usuario), entonces ejecuta
	 * el sistema de gestión administrativo (llama a PantallaPpal).
	 * Si no es administrativo (en Usuario), verifica si se trata de un 
	 * alumno (está en la bd en la tabla Alumno), entonce ejecuta el sistema de
	 * autogestión de alumnos pasándole como parámetro los datos del alumno.
	 * @param evt 
	 */
    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        try {
            
			//conexión con la bd
			UsuarioData usuarioData = new UsuarioData();
			AlumnoData alumnoData = new AlumnoData();
			
			//obtengo los datos de los campos de texto
            String apellido = jTApellido.getText();
            String nombre = jTNombre.getText();
            int dni = Integer.parseInt(new String(jPassword.getPassword()));
			
			//verifico si está en la bd en la tabla de usuarios o de alumnos
			Usuario usuario = usuarioData.getUsuario(apellido, nombre, dni); // intento traer ese usuario. Null es que no está en la bd.
			Alumno alumno = alumnoData.getAlumno(apellido, nombre, dni); // intento traer ese alumno. Null es que no está en la bd
			
			
            if ((apellido.equalsIgnoreCase("ULP")&& nombre.equalsIgnoreCase("admin")&& dni == 12345) //accedo a PantallaPpal con clave maestra
				|| (usuario != null)){ // ese usuario existe en la bd tabla Usuario, por eso no es null
                PantallaPpal pantallaPpal = new PantallaPpal(); //creo una pantallaPpal
				pantallaPpal.setVisible(true); // lo hago visible
				pantallaPpal.setLocationRelativeTo(null); // abrirlo en el centro
				dispose(); //cierra ventana de login
            }else if (alumno != null) { // si no es null es que encontró el alumno. Abre autogestión de alumnos
					AutogestionAlumnos autogestionAlumnos = new AutogestionAlumnos(alumno);
					autogestionAlumnos.setVisible(true);
					autogestionAlumnos.setLocationRelativeTo(null); // abrirlo en el centro
					dispose(); //cierra ventana de login
			} else // no es uuario ni alumno válidos
				JOptionPane.showMessageDialog(null, "Nombre, apellido o clave no corresponden a un usuario válido", "Usuario no existe", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La clave debe ser numerica, verifique los datos ingresados", "Numero no valido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBLoginActionPerformed

	
	
	/**
	 * Este método se llama cuando el usuario hace click en el botón cancel.
	 * @param evt 
	 */
    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        dispose(); //Cerrar la ventana
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
