/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author john
 */
public class PantallaPpal extends javax.swing.JFrame {

	/**
	 * Creates new form PantallaPpal
	 */
	public PantallaPpal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGestionAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuGestionInscripcionesporAlumno = new javax.swing.JMenuItem();
        menuGestionInscripcionesporMateria = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuSalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestión ULP");
        setIconImage(getIconImage());

        escritorio.setPreferredSize(new java.awt.Dimension(900, 610));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");

        menuGestionAlumnos.setText("Gestión de alumnos");
        menuGestionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        menuGestionMaterias.setText("Gestión de materias");
        menuGestionMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(menuGestionMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inscripciones");

        menuGestionInscripcionesporAlumno.setText("Gestión de inscripciones Alumnos por materia");
        menuGestionInscripcionesporAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionInscripcionesporAlumnoActionPerformed(evt);
            }
        });
        jMenu3.add(menuGestionInscripcionesporAlumno);

        menuGestionInscripcionesporMateria.setText("Gestión de inscripciones Materias por alumno");
        menuGestionInscripcionesporMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionInscripcionesporMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(menuGestionInscripcionesporMateria);

        jMenuBar1.add(jMenu3);

        menuSalir.setText("Salir");

        menuSalirSistema.setText("Salir del sistema");
        menuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirSistemaActionPerformed(evt);
            }
        });
        menuSalir.add(menuSalirSistema);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionAlumnosActionPerformed
        escritorio.removeAll(); // cierro todas las ventanas del escritorio
		escritorio.repaint();
		
		GestionAlumnos ga = new GestionAlumnos(); // creo un internal Frame
		ga.setVisible(true); // lo pongo visible
		
		escritorio.add(ga); // lo pongo en el escritorio
		escritorio.moveToFront(ga); //pongo la ventana al frente:
    }//GEN-LAST:event_menuGestionAlumnosActionPerformed

    private void menuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirSistemaActionPerformed
        dispose();//cierra la ventana
		//System.exit(0);// termina el programa
    }//GEN-LAST:event_menuSalirSistemaActionPerformed

    private void menuGestionMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionMateriasActionPerformed
        	escritorio.removeAll(); // cierro todas las ventanas del escritorio
		escritorio.repaint();
		
		GestionMaterias gm = new GestionMaterias(); // creo un internal Frame
		gm.setVisible(true); // lo pongo visible
		
		escritorio.add(gm); // lo pongo en el escritorio
		escritorio.moveToFront(gm); //pongo la ventana al frente:
    }//GEN-LAST:event_menuGestionMateriasActionPerformed

    private void menuGestionInscripcionesporAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionInscripcionesporAlumnoActionPerformed
        escritorio.removeAll(); // cierro todas las ventanas del escritorio
		escritorio.repaint();
		
		GestionInscripciones gi = new GestionInscripciones(); // creo un internal Frame
		gi.setVisible(true); // lo pongo visible
		
		escritorio.add(gi); // lo pongo en el escritorio
		escritorio.moveToFront(gi); //pongo la ventana al frente:
    }//GEN-LAST:event_menuGestionInscripcionesporAlumnoActionPerformed

    private void menuGestionInscripcionesporMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionInscripcionesporMateriaActionPerformed
        escritorio.removeAll(); // cierro todas las ventanas del escritorio
		escritorio.repaint();
		
		GestionInscripcionesMateria gi = new GestionInscripcionesMateria(); // creo un internal Frame
		gi.setVisible(true); // lo pongo visible
		
		escritorio.add(gi); // lo pongo en el escritorio
		escritorio.moveToFront(gi); //pongo la ventana al frente:
    }//GEN-LAST:event_menuGestionInscripcionesporMateriaActionPerformed

	
	@Override
	public Image getIconImage() { // defino el icono del jFrame
		Image retValue = Toolkit.getDefaultToolkit().
				getImage(ClassLoader.getSystemResource("imagenes/ulp_32x32.png")); //icono de la ULP
		return retValue;
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaPpal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuGestionAlumnos;
    private javax.swing.JMenuItem menuGestionInscripcionesporAlumno;
    private javax.swing.JMenuItem menuGestionInscripcionesporMateria;
    private javax.swing.JMenuItem menuGestionMaterias;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuSalirSistema;
    // End of variables declaration//GEN-END:variables
}
